import esbuild from "esbuild";
import { existsSync, readFileSync, statSync, writeFileSync } from "fs";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, open main.ts in this plugin's folder.
*/
`;

const prod = process.argv[2] === "production";
const RELEASE_FILES = ["main.js", "styles.css", "manifest.json"];
const DYNAMIC_SCRIPT_ELEMENT = /createElement\(\s*['"`]script['"`]\s*\)/;

/**
 * PDF.js ships a browser fallback that injects a <script> tag to load
 * `pdf.worker.js`. Obsidian's community review rejects any
 * `createElement('script')` in the bundle, even when that path is unused.
 *
 * Rewrite the vendored builds so the worker is `require()`'d as a bundled
 * module and the script-tag helper is removed. Text extraction is unchanged.
 */
function bundlePdfJsWithoutScriptInjection() {
	return {
		name: "bundle-pdfjs-without-script-injection",
		setup(build) {
			build.onLoad(
				{ filter: /[\\/]pdf-parse[\\/]lib[\\/]pdf\.js[\\/].+[\\/]build[\\/]pdf(?:\.worker)?\.js$/ },
				(args) => {
					let contents = readFileSync(args.path, "utf8");

					contents = contents.replace(
						/Util\.loadScript = function Util_loadScript\(src, callback\) \{[\s\S]*?appendChild\(script\);\s*\};/,
						`Util.loadScript = function Util_loadScript(src, callback) {
    throw new Error("PDF.js cannot load scripts; the worker is bundled as a module.");
  };`
					);

					contents = contents.replace(
						/fakeWorkerFilesLoader = useRequireEnsure \? function \(callback\) \{[\s\S]*?\} : null;/,
						`fakeWorkerFilesLoader = function (callback) {
    var worker = require("./pdf.worker.js");
    callback(worker.WorkerMessageHandler);
  };`
					);

					if (DYNAMIC_SCRIPT_ELEMENT.test(contents)) {
						throw new Error(
							`Failed to strip createElement("script") from ${args.path}`
						);
					}

					return { contents, loader: "js" };
				}
			);
		},
	};
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	// Obsidian provides these at runtime; they must not be bundled in.
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [bundlePdfJsWithoutScriptInjection()],
});

async function packageStyles() {
	if (!existsSync("styles.css")) {
		throw new Error("styles.css is missing from the plugin root.");
	}

	const result = await esbuild.build({
		entryPoints: ["styles.css"],
		bundle: true,
		// Keep the plugin-root stylesheet readable; Obsidian loads this file as-is.
		minify: false,
		write: false,
		logLevel: "info",
	});
	const css = result.outputFiles[0]?.text ?? "";
	if (!css.trim()) {
		throw new Error("styles.css bundled to an empty file.");
	}
	writeFileSync("styles.css", css.endsWith("\n") ? css : `${css}\n`);
}

function assertReleaseArtifacts() {
	for (const file of RELEASE_FILES) {
		if (!existsSync(file) || statSync(file).size === 0) {
			throw new Error(`Release artifact missing or empty: ${file}`);
		}
	}

	const js = readFileSync("main.js", "utf8");
	if (js.includes("sourceMappingURL")) {
		throw new Error("main.js still contains a source map; production builds must be clean.");
	}

	const manifest = JSON.parse(readFileSync("manifest.json", "utf8"));
	const requiredFields = ["id", "name", "version", "minAppVersion", "description", "author"];
	for (const field of requiredFields) {
		if (!manifest[field]) {
			throw new Error(`manifest.json is missing required field: ${field}`);
		}
	}
	if (manifest.id !== "revenue-auditor") {
		throw new Error(`manifest.json id must be "revenue-auditor" (got "${manifest.id}").`);
	}
	if (!/^\d+\.\d+\.\d+$/.test(manifest.version)) {
		throw new Error(`manifest.json version must be a semver string like "1.0.1" (got "${manifest.version}").`);
	}
	if (manifest.minAppVersion !== "1.7.0") {
		throw new Error(`manifest.json minAppVersion must be "1.7.0" (got "${manifest.minAppVersion}").`);
	}
	if (manifest.isDesktopOnly !== true) {
		throw new Error("manifest.json must set isDesktopOnly: true because the plugin uses Node APIs.");
	}
	if (DYNAMIC_SCRIPT_ELEMENT.test(js)) {
		throw new Error("main.js still contains dynamic script-element creation.");
	}

	console.log("Release artifacts ready:");
	for (const file of RELEASE_FILES) {
		console.log(`  - ${file} (${statSync(file).size} bytes)`);
	}
}

if (prod) {
	await context.rebuild();
	await context.dispose();
	await packageStyles();
	assertReleaseArtifacts();
	process.exit(0);
} else {
	await context.watch();
}
